# Generated by Django 3.0.8 on 2021-03-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_api', '0005_auto_20210330_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_creation',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='store',
            name='date_creation',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creación'),
        ),
    ]
