# Generated by Django 3.0.8 on 2021-03-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_api', '0006_auto_20210330_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_creation',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='store',
            name='date_creation',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de creación'),
        ),
    ]
